events {}

http {

    server {

        listen 80;

        location / {

            proxy_pass http://frontend-app;
        }

        location /api/ {

            proxy_pass http://backend-app:3000/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }

}